export { default as CameraIcon } from "./camera.svelte"
export { default as EmailIcon } from "./email.svelte"
export { default as FacebookIcon } from "./facebook.svelte"
// export { default as GitHub } from "./github.svelte"
export { default as LinkedInIcon } from "./linkedin.svelte"
export { default as TelegramIcon } from "./telegram.svelte"
export { default as TiktokIcon } from "./tiktok.svelte"
export { default as TwitterIcon } from "./twitter.svelte"
export { default as WireIcon } from "./wire.svelte"

export { default as ArrowRightIcon } from "./arrow-right.svelte"
export { default as CheckIcon } from "./check.svelte"
export { default as CopyIcon } from "./copy.svelte"
export { default as DiscordIcon } from "./discord.svelte"
export { default as ExpandIcon } from "./expand.svelte"
export { default as GithubIcon } from "./github.svelte"
export { default as GlobeIcon } from "./globe.svelte"
export { default as InformationIcon } from "./information-circle.svelte"
export { default as MenuIcon } from "./menu.svelte"
export { default as MoonIcon } from "./moon.svelte"
export { default as SpinnerIcon } from "./spinner.svelte"
export { default as SunIcon } from "./sun.svelte"
export { default as WordWrapIcon } from "./word-wrap.svelte"
export { default as XIcon } from "./x.svelte"
